# Generated by Django 3.2.18 on 2023-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0002_candidate_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.CharField(max_length=30)),
                ('result_status', models.IntegerField()),
            ],
        ),
    ]
