# Generated by Django 3.2.18 on 2023-04-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0003_voteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.CharField(max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVotingApp.candidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVotingApp.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVotingApp.user')),
            ],
        ),
    ]
