# Generated by Django 3.2.18 on 2024-03-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0005_remove_vote_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
